name: Keep Alive

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 5 minutes
  workflow_dispatch:  # Allow manual triggers

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping website
        run: |
          response_code=$(curl -s -o /dev/null -w "%{http_code}" https://moviebot4-dhibi9836.koyeb.app/)
          if [ "$response_code" -ne 200 ]; then
            echo "Website returned status code $response_code"
            exit 1
          else
            echo "Website pinged successfully"
          fi
